_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.7.16
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 63
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 63
            "3":
                - 13
                - 16
                - 23
                - 55
                - 62
            "4": 3.7.16
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size:
    value: 16
c:
    value: ./configs/KEY_SwinT.yaml
data_size:
    value: 384
device:
    value: cuda:2
eval_freq:
    value: 10
exp_name:
    value: T3000
fpn_size:
    value: 1536
lambda_b:
    value: 0.5
lambda_c:
    value: 1
lambda_n:
    value: 5
lambda_s:
    value: 0
log_freq:
    value: 100
max_epochs:
    value: 50
max_lr:
    value: 0.0005
model_name:
    value: swin-t
num_classes:
    value: 19
num_selects:
    value:
        layer1: 2048
        layer2: 512
        layer3: 128
        layer4: 32
num_workers:
    value: 2
optimizer:
    value: SGD
pretrained:
    value: null
project_name:
    value: KEY-T2
save_dir:
    value: ./records/KEY-T2/T3000/
train_root:
    value: /data1/wdh/FGVC_DataandModel/train_sam_datainit/
update_freq:
    value: 2
use_amp:
    value: true
use_combiner:
    value: true
use_fpn:
    value: true
use_selection:
    value: true
use_wandb:
    value: true
val_root:
    value: /data1/wdh/FGVC_DataandModel/val_sam_datainit/
wandb_entity:
    value: 2637607099-east-china-normal-university
warmup_batchs:
    value: 800
wdecay:
    value: 0.0005
