project_name: NABirds-SWINT-FEMCC
exp_name: T4GCN
use_wandb: True
wandb_entity: xxxxxx
# train_root: ../datas/train/
train_root: /data1/wdh/FGVC_DataandModel/NABirds/train/
# train_root: ~
# val_root: ../datas/test/
val_root: /data1/wdh/FGVC_DataandModel/NABirds/test/
data_size: 384
num_workers: 2
batch_size: 8
model_name: swin-t
pretrained: ~
# pretrained: /data1/wdh/FEM-CC-ALL/FEM-CC/records/NABirds-SWINT92628AND9251/T4/backup/best.pt
optimizer: SGD
max_lr: 0.0005
wdecay: 0.0003
max_epochs: 50
warmup_batchs: 1200
use_amp: True
use_fpn: True
fpn_size: 1536
use_selection: True
num_classes: 555
num_selects: 
  layer1: 256
  layer2: 128
  layer3: 64
  layer4: 32
use_combiner: True
lambda_b: 0.5
lambda_s: 0.0
lambda_n: 3.0
lambda_c: 1.0
update_freq: 2
log_freq: 100
eval_freq: 10
dim: 1536
lmd_1: 1.7
lmd_2: 0.6
